### ISSUE TITLE
安卓

### ISSUE THREAD

**Issue by Flysky12138** [onplus/v2ray-SiteDAT#2]
能否提供一个安卓可执行的文件[不会编译]

**Comment by drumfysh** [comment]
编译了一个在安卓termux上运行的，[https://github.com/drumfysh/v2ray-SiteDAT/releases/tag/0.1](url)

**Comment by drumfysh** [comment]
> 能否提供一个安卓可执行的文件[不会编译]

编译了一个在安卓termux上运行的，[v2raysite_for_termux](https://github.com/drumfysh/v2ray-SiteDAT/releases/tag/0.1)
